### ISSUE TITLE
ícones para os 5 jogos em amarelo, vermelho, azul e roxo

### ISSUE THREAD

**Issue by nafergo** [nafergo/projeto-arco-iris#10]
ícones para os 5 jogos em amarelo, vermelho, azul e roxo

**Comment by pholdrep** [comment]
Ícones a cores dos 5 jogos.

[icon_games.zip](https://github.com/nafergo/projeto-arco-iris/files/216050/icon_games.zip)

![icones](https://cloud.githubusercontent.com/assets/14826176/14477340/16f70220-0105-11e6-872e-b3dc5bf6386a.png)
