### ISSUE TITLE
info adultos

### ISSUE THREAD

**Issue by nafergo** [nafergo/projeto-arco-iris#3]
- texto da aida

**Comment by AidaRebelo** [comment]
O programa de estimulação sócio emocional pretende trabalhar quer o reconhecimento das próprias emoções (autoconsciência), quer o recolhimento das emoções nos outros (empatia). Este programa é destinado a crianças com necessidades educativas especiais, mais concretamente com incapacidade intelectual ligeira ou moderada. No entanto, pode ser utilizado com as demais crianças, pois o desenvolvimento emocional é fulcral no desenvolvimento, uma vez que permite à criança responder de forma ajustada às várias situações do dia-a-dia, compreendendo e gerindo as suas próprias emoções. A capacidade da criança expressar as suas emoções de modo adequado é fundamental ao longo do seu desenvolvimento, bem como no desenrolar das relações interpessoais, pois à medida que vai conhecendo as expressões emocionais e os comportamentos e situações que ativam diversas emoções, conseguem armazenar na memória os aspetos relacionados com as expressões de ordem emocional, mostrando-se capaz de compreender as suas emoções e as dos outros.
Este programa configura-se como uma excelente ferramenta de trabalho para psicólogos que trabalham com crianças com NEE, pois de uma forma lúdica e atrativa a criança aprende a lidar com diversas situações emocionais e adquire hábitos emocionais. O programa pretende trabalhar as quatro emoções básicas, nomeadamente alegria, tristeza, medo e raiva no próprio e nos outros. Ao longo do software a criança tem a oportunidade de explorar as diversas emoções e consolidar as aprendizagens através da interação com jogos e a resolução de diferentes situações sociais.
